[build]
  publish = "Lifecraft---MVP"

[[redirects]]
  from = "/apply"
  to = "/apply.html"
  status = 200

[[redirects]]
  from = "/assessment"
  to = "/assessment.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
